### ISSUE TITLE
Failed to fetch data from server

### ISSUE THREAD

**Issue by AraaCuteUwU** [ZenthicMC/laravel-films-store#1]
https://flareapp.io/share/v5p1relm#F51

**Comment by zenthicmc** [comment]
itu karena gagal nge fetch data dari server tripay, makanya undefined datanya. pastikan konfigurasi udah bener (key & url)

**Comment by zenthicmc** [comment]
+ cek docs tripay, apakah ada update. (tripay sering update docs nya yg menyebabkan beberapa kodingan lama ga berfungsi)
